/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/state-changed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle state changed
         * @description State changed.
         */
        post: operations["StateChanged"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/update-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update payment amount in response to changes
         * @description Hook on changes to update payment.
         */
        post: operations["UpdatePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout/v1/orders/{order_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new Awardit giftcard
         * @description Requires an existing Norce order.
         */
        post: operations["CreateAwarditPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout/v1/orders/{order_id}/payments/{payment_id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove a Awardit giftcard
         * @description Requires an existing Norce order. Will do soft delete on any payments or shippings by setting state to removed. Will delete any hooks added when creating an Awardit payment.
         */
        post: operations["RemoveAwarditPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Addon: {
            /** Format: double */
            price?: number;
            reference?: string;
        };
        Address: {
            attributes?: {
                [key: string]: unknown;
            };
            careOf?: string;
            city?: string;
            country?: string;
            email?: string;
            familyName?: string;
            givenName?: string;
            nationalIdentificationNumber?: string;
            organizationIdentificationNumber?: string;
            organizationName?: string;
            phone?: string;
            postalCode?: string;
            reference?: string;
            region?: string;
            streetAddress?: string;
            streetAddress2?: string;
            type?: components["schemas"]["CustomerType"];
        };
        AwarditError: {
            correlationId?: string;
            errorCode?: string;
            errorMessages?: string[];
        };
        Cart: {
            attributes?: {
                [key: string]: unknown;
            };
            discounts?: components["schemas"]["Discount"][];
            items?: components["schemas"]["Item"][];
            reference?: string;
            total?: components["schemas"]["Price"];
        };
        Consent: {
            checked?: boolean;
            id?: string;
            required?: boolean;
            text?: string;
        };
        Customer: {
            attributes?: {
                [key: string]: unknown;
            };
            billing?: components["schemas"]["Address"];
            shipping?: components["schemas"]["Address"];
            type?: components["schemas"]["CustomerType"];
        };
        /** @enum {string} */
        CustomerType: "person" | "organization";
        DeliveryDetails: {
            carrier?: string;
            class?: string;
            pickupLocation?: components["schemas"]["PickupLocation"];
            product?: components["schemas"]["Product"];
        };
        Discount: {
            attributes?: {
                [key: string]: unknown;
            };
            code?: string;
            name?: string;
            type?: components["schemas"]["DiscountType"];
            value?: components["schemas"]["Price"];
        };
        /** @enum {string} */
        DiscountType: "item" | "shipping";
        Error: {
            /** @description Error if originating from Resurs Bank */
            awarditError?: components["schemas"]["AwarditError"];
            /**
             * @description Error code
             * @example cart-not-found
             * @enum {string}
             */
            code?: "internal-server-error" | "unauthorized" | "configuration-error" | "configuration-not-found" | "order-not-found" | "order-error" | "order-bad-request" | "order-conflict" | "order-validation" | "shipping-not-found" | "shipping-error" | "payment-not-found" | "payment-error" | "payment-conflict" | "awardit-error" | "awardit-bad-request" | "awardit-validation" | "awardit-card-not-found" | "awardit-missing-pin" | "awardit-card-empty" | "translation-not-found";
            /**
             * @description Detailed error information
             * @example Cart with id:{id} now found.
             */
            message?: string;
        };
        GiftCard: {
            cardId?: string;
            code?: string;
        };
        Hook: {
            adapterId?: string;
            id?: string;
            invoke?: string;
            subscribeTo?: string;
            target?: string;
        };
        Item: {
            attributes?: {
                [key: string]: unknown;
            };
            discounts?: components["schemas"]["Discount"][];
            id?: string;
            imageUrl?: string;
            name?: string;
            originalTotal?: components["schemas"]["Price"];
            price?: components["schemas"]["Price"];
            /** Format: int32 */
            quantity?: number;
            reference?: string;
            sku?: string;
            total?: components["schemas"]["Price"];
            unit?: string;
            url?: string;
            /** Format: double */
            vatRate?: number;
        };
        NorceOrder: {
            attributes?: {
                [key: string]: unknown;
            };
            cart?: components["schemas"]["Cart"];
            channel?: string;
            consents?: components["schemas"]["Consent"][];
            country?: string;
            /** Format: date-time */
            created?: string;
            culture?: string;
            currency?: string;
            customer?: components["schemas"]["Customer"];
            hooks?: components["schemas"]["Hook"][];
            id?: string;
            /** Format: date-time */
            lastModified?: string;
            merchant?: string;
            payments?: components["schemas"]["Payment"][];
            reference?: string;
            shippings?: components["schemas"]["Shipping"][];
            state?: components["schemas"]["State"];
            total?: components["schemas"]["Price"];
        };
        /** @enum {string} */
        OrderStatus: "checkout" | "processing" | "accepted" | "completed" | "declined" | "removed";
        PatchOperation: {
            op?: string;
            path?: string;
            value?: unknown;
        };
        Payment: {
            adapterId?: string;
            /** Format: double */
            amount?: number;
            attributes?: {
                [key: string]: unknown;
            };
            channel?: string;
            currency?: string;
            id?: string;
            merchant?: string;
            name?: string;
            orderId?: string;
            reference?: string;
            state?: components["schemas"]["PaymentState"];
            type?: components["schemas"]["PaymentType"];
            /** Format: double */
            upperLimitAmount?: number;
        };
        /** @enum {string} */
        PaymentState: "intent" | "removed" | "processing" | "failed" | "confirmed" | "pending" | "declined" | "reserved" | "credited" | "captured" | "cancelled" | "refunded";
        /** @enum {string} */
        PaymentType: "default" | "prepaid" | "voucher";
        PickupLocation: {
            address?: components["schemas"]["PickupLocationAddress"];
            name?: string;
            reference?: string;
        };
        PickupLocationAddress: {
            city?: string;
            country?: string;
            postalCode?: string;
            streetAddress?: string;
        };
        Price: {
            /** Format: double */
            excludingVat?: number;
            /** Format: double */
            includingVat?: number;
        };
        ProblemDetails: {
            detail?: string;
            instance?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
            type?: string;
        } & {
            [key: string]: unknown;
        };
        Product: {
            name?: string;
            reference?: string;
        };
        Shipping: {
            adapterId?: string;
            addons?: components["schemas"]["Addon"][];
            attributes?: {
                [key: string]: unknown;
            };
            channel?: string;
            deliveryDetails?: components["schemas"]["DeliveryDetails"];
            id?: string;
            merchant?: string;
            name?: string;
            orderId?: string;
            reference?: string;
            state?: components["schemas"]["ShippingState"];
            tmsReference?: string;
            total?: components["schemas"]["Price"];
            /** Format: double */
            vatRate?: number;
        };
        /** @enum {string} */
        ShippingState: "intent" | "removed" | "processing" | "failed" | "confirmed";
        State: {
            currentStatus?: components["schemas"]["OrderStatus"];
            transitions?: components["schemas"]["Transition"][];
        };
        Transition: {
            status?: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            timeStamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type Addon = components['schemas']['Addon'];
export type Address = components['schemas']['Address'];
export type AwarditError = components['schemas']['AwarditError'];
export type Cart = components['schemas']['Cart'];
export type Consent = components['schemas']['Consent'];
export type Customer = components['schemas']['Customer'];
export type CustomerType = components['schemas']['CustomerType'];
export type DeliveryDetails = components['schemas']['DeliveryDetails'];
export type Discount = components['schemas']['Discount'];
export type DiscountType = components['schemas']['DiscountType'];
export type Error = components['schemas']['Error'];
export type GiftCard = components['schemas']['GiftCard'];
export type Hook = components['schemas']['Hook'];
export type Item = components['schemas']['Item'];
export type NorceOrder = components['schemas']['NorceOrder'];
export type OrderStatus = components['schemas']['OrderStatus'];
export type PatchOperation = components['schemas']['PatchOperation'];
export type Payment = components['schemas']['Payment'];
export type PaymentState = components['schemas']['PaymentState'];
export type PaymentType = components['schemas']['PaymentType'];
export type PickupLocation = components['schemas']['PickupLocation'];
export type PickupLocationAddress = components['schemas']['PickupLocationAddress'];
export type Price = components['schemas']['Price'];
export type ProblemDetails = components['schemas']['ProblemDetails'];
export type Product = components['schemas']['Product'];
export type Shipping = components['schemas']['Shipping'];
export type ShippingState = components['schemas']['ShippingState'];
export type State = components['schemas']['State'];
export type Transition = components['schemas']['Transition'];
export type $defs = Record<string, never>;
export interface operations {
    StateChanged: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Channel identifier
                 * @example 1
                 */
                "x-channel": string;
                /**
                 * @description Merchant identifier.
                 * @example norce
                 */
                "x-merchant": string;
            };
            path: {
                /** @description Order identifier */
                order_id: string;
                /** @description Payment identifier */
                payment_id: string;
            };
            cookie?: never;
        };
        /** @description Updated order */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NorceOrder"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchOperation"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    UpdatePayment: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Channel identifier
                 * @example 1
                 */
                "x-channel": string;
                /**
                 * @description Merchant identifier.
                 * @example norce
                 */
                "x-merchant": string;
            };
            path: {
                /** @description Order identifier */
                order_id: string;
                /** @description Payment identifier */
                payment_id: string;
            };
            cookie?: never;
        };
        /** @description Updated order */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NorceOrder"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchOperation"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CreateAwarditPayment: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Channel identifier
                 * @example 1
                 */
                "x-channel": string;
                /**
                 * @description Merchant identifier.
                 * @example norce
                 */
                "x-merchant": string;
            };
            path: {
                /** @description Order identifier */
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GiftCard"];
            };
        };
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    RemoveAwarditPayment: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Channel identifier
                 * @example 1
                 */
                "x-channel": string;
                /**
                 * @description Merchant identifier.
                 * @example norce
                 */
                "x-merchant": string;
            };
            path: {
                /** @description Order identifier */
                order_id: string;
                /** @description Payment identifier */
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
