/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/cart-changed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Handle Cart changed
     * @deprecated
     * @description Cart changed.
     */
    post: operations['CartChanged'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/customer-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh customer information on Norce order from qliro order
     * @description Updates customer information on Norce order with latest customer information from Qliro Checkout
     */
    post: operations['UpdateCustomerFromQliroCheckout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/notification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     *     Qliro will use this URL to send notifications for general status updates.
     *     For example if you are using integrated shipping providers (e.g. nShift or Ingrid)
     *     this url will be called when we complete or if we get an error from the shipping provider api:s.
     * @description Called whenever a Qliro order’s is complete or if we get an error from the shipping provider api:s.
     */
    post: operations['Notification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/push': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Push
     * @description Called whenever a Qliro order’s CheckoutOrderStatus is changed
     */
    post: operations['Push'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/save-recurring-details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Saves the customer's payment details for a recurring order.
     * @description Called when a user agrees to save their payment details for recurring payments.
     */
    post: operations['SaveRecurringPaymentDetails'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/shipping-option-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Shipping option update. The Norce order will be updated with the latest selected delivery information from qliro
     * @description Shipping option updated notifications. Will update the Norce order with latest shipping selection from qliro
     */
    post: operations['ShippingOptionUpdate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/state-changed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Handle State changed
     * @description State changed.
     */
    post: operations['StateChanged'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Qliro will send a notification to MerchantOrderManagementStatusPushUrl whenever the status of an Admin API request changed status.
     * @description Called  whenever the status of an Admin API request changed status on the Qliro order
     */
    post: operations['OrderManagementStatus'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/update-payment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Handle order changes
     * @description Responds with patch for updated payment given an updated order.
     */
    post: operations['UpdatePayment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/upsell/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ends the upsell period for a specific payment and completes the order.
     * @description Complete Upsell.
     */
    post: operations['CompleteUpsell'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/callback/orders/{order_id}/payments/{payment_id}/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate */
    post: operations['Validate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/orders/{order_id}/payments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new Qliro Checkout order
     * @description Requires an existing Norce order.
     */
    post: operations['CreateQliroCheckoutOrderPayment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/orders/{order_id}/payments/{payment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an existing Qliro Checkout order
     * @description Used to get the html snippet, for example after the Qliro Checkout Order has been confirmed.
     */
    get: operations['GetQliroCheckoutOrderPayment'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/orders/{order_id}/payments/{payment_id}/remove': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Remove a Qliro Checkout order
     * @description Requires an existing Norce order. Will do soft delete on any payments or shippings by setting state to removed. Will delete any hooks added when creating a Qliro Checkout order.
     */
    post: operations['RemoveQliroCheckoutOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/checkout/v1/orders/{order_id}/payments/recurring': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new Qliro Checkout order using a recurring token from a previous Qliro purchase.
     * @description Requires an existing Norce order and Qliro recurring token
     */
    post: operations['CreateQliroCheckoutRecurringOrderPayment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/order/v1/orders/{order_id}/payments/{payment_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Qliro Order
     * @description Used to cancel a Qliro order
     */
    post: operations['CancelOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/order/v1/orders/{order_id}/payments/{payment_id}/capture': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Capture Qliro order
     * @description Used to capture a Qliro order
     */
    post: operations['CaptureOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/order/v1/orders/{order_id}/payments/{payment_id}/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh the list of available PaymentActions for an order
     * @description Refreshes the list of available payment actions on payment, to reflect the current payment state
     */
    post: operations['Refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/order/v1/orders/{order_id}/payments/{payment_id}/refund': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refund Qliro order
     * @description Used to refund a Qliro order
     */
    post: operations['RefundOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    Addon: {
      /** Format: double */
      price?: number;
      reference?: string;
    };
    Address: {
      attributes?: {
        [key: string]: unknown;
      };
      careOf?: string;
      city?: string;
      country?: string;
      email?: string;
      familyName?: string;
      givenName?: string;
      nationalIdentificationNumber?: string;
      organizationIdentificationNumber?: string;
      organizationName?: string;
      phone?: string;
      postalCode?: string;
      reference?: string;
      region?: string;
      streetAddress?: string;
      streetAddress2?: string;
      type?: components['schemas']['CustomerType'];
    };
    Cart: {
      attributes?: {
        [key: string]: unknown;
      };
      discounts?: components['schemas']['Discount'][];
      items?: components['schemas']['Item'][];
      reference?: string;
      total?: components['schemas']['Price'];
    };
    Consent: {
      checked?: boolean;
      id?: string;
      required?: boolean;
      text?: string;
    };
    Customer: {
      attributes?: {
        [key: string]: unknown;
      };
      billing?: components['schemas']['Address'];
      shipping?: components['schemas']['Address'];
      type?: components['schemas']['CustomerType'];
    };
    /** @enum {string} */
    CustomerCheckoutStatus:
      | 'inProcess'
      | 'completed'
      | 'onHold'
      | 'refused'
      | 'success';
    /** @enum {string} */
    CustomerType: 'person' | 'organization';
    DeliveryDetails: {
      carrier?: string;
      class?: string;
      pickupLocation?: components['schemas']['PickupLocation'];
      product?: components['schemas']['Product'];
    };
    Discount: {
      attributes?: {
        [key: string]: unknown;
      };
      code?: string;
      name?: string;
      type?: components['schemas']['DiscountType'];
      value?: components['schemas']['Price'];
    };
    /** @enum {string} */
    DiscountType: 'item' | 'shipping';
    Error: {
      /**
       * @description Error code
       * @example cart-not-found
       * @enum {string}
       */
      code?:
        | 'internal-server-error'
        | 'unauthorized'
        | 'configuration-error'
        | 'configuration-not-found'
        | 'order-not-found'
        | 'order-error'
        | 'order-bad-request'
        | 'order-conflict'
        | 'order-validation'
        | 'order-unknown-validation-error'
        | 'shipping-not-found'
        | 'shipping-error'
        | 'payment-not-found'
        | 'payment-error'
        | 'payment-conflict'
        | 'qliro-error'
        | 'qliro-bad-request'
        | 'qliro-order-expired'
        | 'qliro-validation'
        | 'qliro-order-not-found'
        | 'translation-not-found';
      /**
       * @description Detailed error information
       * @example Cart with id:{id} now found.
       */
      message?: string;
      /** @description Error if originating from Qliro */
      qliroError?: components['schemas']['QliroError'];
    };
    GetOrderResponse: {
      AskForNewsletterSignupChecked?: boolean;
      BillingAddress?: components['schemas']['QliroAddress'];
      Country?: string;
      Currency?: string;
      Customer?: components['schemas']['QliroCustomer'];
      CustomerCheckoutStatus?: components['schemas']['CustomerCheckoutStatus'];
      IdentityVerification?: components['schemas']['IdentityVerification'];
      Language?: string;
      MerchantProvidedMetadata?: components['schemas']['MerchantProvidedMetadata'][];
      MerchantReference?: string;
      MerchantSavedCreditCard?: components['schemas']['MerchantSavedCreditCard'];
      OrderHtmlSnippet?: string;
      /** Format: int32 */
      OrderId?: number;
      OrderItems?: components['schemas']['OrderItem'][];
      PaymentMethod?: components['schemas']['PaymentMethod'];
      SelectedShippingMethod?: string;
      SelectedShippingSecondaryOption?: string;
      ShippingAddress?: components['schemas']['QliroAddress'];
      SignupForNewsletter?: boolean;
      /** Format: double */
      TotalPrice?: number;
      Upsell?: components['schemas']['QliroUpsell'];
      UpsellId?: string;
    };
    Hook: {
      adapterId?: string;
      id?: string;
      invoke?: string;
      subscribeTo?: string;
      target?: string;
    };
    IdentityVerification: {
      IdentityVerified?: boolean;
      RequireIdentityVerification?: boolean;
    };
    Item: {
      attributes?: {
        [key: string]: unknown;
      };
      discounts?: components['schemas']['Discount'][];
      id?: string;
      imageUrl?: string;
      logistics?: components['schemas']['Logistics'];
      name?: string;
      originalTotal?: components['schemas']['Price'];
      price?: components['schemas']['Price'];
      /** Format: int32 */
      quantity?: number;
      reference?: string;
      sku?: string;
      total?: components['schemas']['Price'];
      unit?: string;
      upsell?: boolean;
      url?: string;
      /** Format: double */
      vatRate?: number;
    };
    Logistics: {
      /** Format: int32 */
      height?: number;
      /** Format: int32 */
      length?: number;
      /** Format: date-time */
      shippingDate?: string;
      tags?: string[];
      /** Format: int32 */
      weight?: number;
      /** Format: int32 */
      width?: number;
    };
    MerchantProvidedMetadata: {
      Key?: string;
      Value?: string;
    };
    MerchantSavedCreditCard: {
      bin?: string;
      brandName?: string;
      /** Format: int32 */
      expiryMonth?: number;
      /** Format: int32 */
      expiryYear?: number;
      id?: string;
      last4Digits?: string;
      maskedNumber?: string;
    };
    NorceOrder: {
      attributes?: {
        [key: string]: unknown;
      };
      cart?: components['schemas']['Cart'];
      channel?: string;
      consents?: components['schemas']['Consent'][];
      country?: string;
      /** Format: date-time */
      created?: string;
      culture?: string;
      currency?: string;
      customer?: components['schemas']['Customer'];
      hooks?: components['schemas']['Hook'][];
      id?: string;
      /** Format: date-time */
      lastModified?: string;
      merchant?: string;
      notifications?: components['schemas']['Notification'][];
      payments?: components['schemas']['Payment'][];
      reference?: string;
      shippings?: components['schemas']['Shipping'][];
      state?: components['schemas']['State'];
      total?: components['schemas']['Price'];
    };
    Notification: {
      adapterId?: string;
      /** Format: int32 */
      delay?: number;
      description?: string;
      id?: string;
      invoke?: string;
      reference?: string;
      schema?: {
        [key: string]: unknown;
      };
      scope?: string;
    };
    OrderItem: {
      Description?: string;
      MerchantReference?: string;
      /** Format: int32 */
      PaymentTransactionId?: number;
      /** Format: double */
      PricePerItemExVat?: number;
      /** Format: double */
      PricePerItemIncVat?: number;
      /** Format: int32 */
      Quantity?: number;
      Type?: components['schemas']['OrderItemType'];
      UpsellId?: string;
    };
    /** @enum {string} */
    OrderItemType: 'product' | 'discount' | 'fee' | 'shipping';
    /** @enum {string} */
    OrderStatus:
      | 'checkout'
      | 'processing'
      | 'accepted'
      | 'completed'
      | 'declined'
      | 'removed';
    PatchOperation: {
      op?: string;
      path?: string;
      value?: unknown;
    };
    Payment: {
      actions?: components['schemas']['PaymentAction'][];
      adapterId?: string;
      /** Format: double */
      amount?: number;
      attributes?: {
        [key: string]: unknown;
      };
      channel?: string;
      currency?: string;
      id?: string;
      merchant?: string;
      name?: string;
      orderId?: string;
      recurring?: components['schemas']['Recurring'];
      reference?: string;
      state?: components['schemas']['PaymentState'];
      type?: components['schemas']['PaymentType'];
      /** Format: double */
      upperLimitAmount?: number;
      upsell?: components['schemas']['Upsell'];
    };
    PaymentAction: {
      adapterId?: string;
      id?: string;
      type?: string;
      url?: string;
    };
    PaymentMethod: {
      PaymentMethodName?: string;
      PaymentTypeCode?: string;
    };
    /** @enum {string} */
    PaymentState:
      | 'intent'
      | 'removed'
      | 'processing'
      | 'failed'
      | 'confirmed'
      | 'pending'
      | 'declined'
      | 'reserved'
      | 'credited'
      | 'captured'
      | 'cancelled'
      | 'refunded';
    /** @enum {string} */
    PaymentType: 'default' | 'prepaid' | 'voucher';
    PickupLocation: {
      address?: components['schemas']['PickupLocationAddress'];
      name?: string;
      reference?: string;
    };
    PickupLocationAddress: {
      city?: string;
      country?: string;
      postalCode?: string;
      streetAddress?: string;
    };
    Price: {
      /** Format: double */
      excludingVat?: number;
      /** Format: double */
      includingVat?: number;
    };
    ProblemDetails: {
      detail?: string;
      instance?: string;
      /** Format: int32 */
      status?: number;
      title?: string;
      type?: string;
    } & {
      [key: string]: unknown;
    };
    Product: {
      name?: string;
      reference?: string;
    };
    QliroAddress: {
      Area?: string;
      AreaCode?: string;
      CareOf?: string;
      City?: string;
      CompanyName?: string;
      CountryCode?: string;
      FirstName?: string;
      LastName?: string;
      PostalCode?: string;
      Street?: string;
      Street2?: string;
    };
    QliroCheckoutNotificationRequest: {
      ErrorMessage?: string;
      EventType?: string;
      IsSuccess?: boolean;
      MerchantReference?: string;
      /** Format: int64 */
      OrderId?: number;
      Payload?: unknown;
      Provider?: string;
      /** Format: date-time */
      Timestamp?: string;
    };
    QliroCheckoutOrder: {
      /**
       * @description Qliro checkout order html snippet.
       * @example
       */
      htmlSnippet?: string;
      /** @description Norce Payment Id */
      paymentId?: string;
    };
    QliroCheckoutPushRequest: {
      merchantReference?: string;
      notificationType?: string;
      /** Format: int64 */
      orderId?: number;
      /** Format: int64 */
      originalPaymentTransactionId?: number;
      /** Format: int64 */
      paymentTransactionId?: number;
      replacesOriginalPaymentTransaction?: boolean;
      status?: string;
      /** Format: date-time */
      timestamp?: string;
      upsellId?: string;
    };
    QliroCheckoutPushResponse: {
      callbackResponse?: string;
    };
    QliroCheckoutRecurringOrder: {
      /** @description Norce Payment Id */
      paymentId?: string;
    };
    QliroCheckoutShippingMethodChanged: {
      additionalShippingServices?: string[];
      method?: string;
      methodName?: string;
      pickupLocation?: components['schemas']['QliroCheckoutShippingMethodChangedPickupLocation'];
      /**
       * Format: double
       * @description Represents the price of the shipping method selected
       */
      price?: number;
      /** Format: double */
      priceExVat?: number;
      secondaryOption?: string;
      shippingServicesNames?: string[];
      /**
       * Format: double
       * @description Price of the shipping method selected plus any additionalServices that might cost extra
       */
      totalShippingPrice?: number;
      /** Format: double */
      totalShippingPriceExVat?: number;
    };
    QliroCheckoutShippingMethodChangedPickupLocation: {
      description?: string[];
      name?: string;
    };
    QliroCheckoutValidationErrorResponse: {
      declineReasonMessage?: string;
    };
    QliroCustomer: {
      DateOfBirth?: string;
      Email?: string;
      FirstName?: string;
      /** Format: int32 */
      Gender?: number;
      JuridicalType?: components['schemas']['QliroCustomerType'];
      LastName?: string;
      MobileNumber?: string;
      PersonalNumber?: string;
      VatNumber?: string;
    };
    /** @enum {string} */
    QliroCustomerType: 'physical' | 'company';
    QliroError: {
      errorCode?: string;
      errorMessage?: string;
      errorReference?: string;
    };
    QliroOrderManagementStatusRequest: {
      /** Format: double */
      Amount?: number;
      Currency?: string;
      ErrorCode?: string;
      ErrorCodeDescription?: string;
      MerchantReference?: string;
      /** Format: int64 */
      OrderID?: number;
      /** Format: int64 */
      OriginalPaymentTransactionId?: number;
      /** Format: int64 */
      PaymentReference?: number;
      /** Format: int64 */
      PaymentTransactionId?: number;
      PaymentType?: string;
      ProviderResultCode?: string;
      ProviderResultDescription?: string;
      ProviderTransactionId?: string;
      Status?: string;
      TimeStamp?: string;
    };
    QliroUpsell: {
      eligibleForUpsell?: boolean;
      /** Format: date-time */
      eligibleForUpsellUntil?: string;
      isUpsellOrder?: boolean;
      /** Format: double */
      upsellTotalPrice?: number;
    };
    Recurring: {
      attributes?: {
        [key: string]: unknown;
      };
      description?: string;
      token?: string;
    };
    RecurringTokenModel: {
      token?: string;
    };
    Shipping: {
      adapterId?: string;
      addons?: components['schemas']['Addon'][];
      attributes?: {
        [key: string]: unknown;
      };
      channel?: string;
      deliveryDetails?: components['schemas']['DeliveryDetails'];
      id?: string;
      merchant?: string;
      name?: string;
      orderId?: string;
      reference?: string;
      state?: components['schemas']['ShippingState'];
      tmsReference?: string;
      total?: components['schemas']['Price'];
      /** Format: double */
      vatRate?: number;
    };
    /** @enum {string} */
    ShippingState: 'intent' | 'removed' | 'processing' | 'failed' | 'confirmed';
    State: {
      currentStatus?: components['schemas']['OrderStatus'];
      transitions?: components['schemas']['Transition'][];
    };
    Transition: {
      status?: components['schemas']['OrderStatus'];
      /** Format: date-time */
      timeStamp?: string;
    };
    Upsell: {
      attributes?: {
        [key: string]: unknown;
      };
      eligible?: boolean;
      /** Format: date-time */
      expiration?: string;
      transactions?: components['schemas']['UpsellTransaction'][];
    };
    /** @enum {string} */
    UpsellState: 'created' | 'actionRequired' | 'completed' | 'failed';
    UpsellTransaction: {
      attributes?: {
        [key: string]: unknown;
      };
      id?: string;
      itemIds?: string[];
      state?: components['schemas']['UpsellState'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type Addon = components['schemas']['Addon'];
export type Address = components['schemas']['Address'];
export type Cart = components['schemas']['Cart'];
export type Consent = components['schemas']['Consent'];
export type Customer = components['schemas']['Customer'];
export type CustomerCheckoutStatus =
  components['schemas']['CustomerCheckoutStatus'];
export type CustomerType = components['schemas']['CustomerType'];
export type DeliveryDetails = components['schemas']['DeliveryDetails'];
export type Discount = components['schemas']['Discount'];
export type DiscountType = components['schemas']['DiscountType'];
export type Error = components['schemas']['Error'];
export type GetOrderResponse = components['schemas']['GetOrderResponse'];
export type Hook = components['schemas']['Hook'];
export type IdentityVerification =
  components['schemas']['IdentityVerification'];
export type Item = components['schemas']['Item'];
export type Logistics = components['schemas']['Logistics'];
export type MerchantProvidedMetadata =
  components['schemas']['MerchantProvidedMetadata'];
export type MerchantSavedCreditCard =
  components['schemas']['MerchantSavedCreditCard'];
export type NorceOrder = components['schemas']['NorceOrder'];
export type Notification = components['schemas']['Notification'];
export type OrderItem = components['schemas']['OrderItem'];
export type OrderItemType = components['schemas']['OrderItemType'];
export type OrderStatus = components['schemas']['OrderStatus'];
export type PatchOperation = components['schemas']['PatchOperation'];
export type Payment = components['schemas']['Payment'];
export type PaymentAction = components['schemas']['PaymentAction'];
export type PaymentMethod = components['schemas']['PaymentMethod'];
export type PaymentState = components['schemas']['PaymentState'];
export type PaymentType = components['schemas']['PaymentType'];
export type PickupLocation = components['schemas']['PickupLocation'];
export type PickupLocationAddress =
  components['schemas']['PickupLocationAddress'];
export type Price = components['schemas']['Price'];
export type ProblemDetails = components['schemas']['ProblemDetails'];
export type Product = components['schemas']['Product'];
export type QliroAddress = components['schemas']['QliroAddress'];
export type QliroCheckoutNotificationRequest =
  components['schemas']['QliroCheckoutNotificationRequest'];
export type QliroCheckoutOrder = components['schemas']['QliroCheckoutOrder'];
export type QliroCheckoutPushRequest =
  components['schemas']['QliroCheckoutPushRequest'];
export type QliroCheckoutPushResponse =
  components['schemas']['QliroCheckoutPushResponse'];
export type QliroCheckoutRecurringOrder =
  components['schemas']['QliroCheckoutRecurringOrder'];
export type QliroCheckoutShippingMethodChanged =
  components['schemas']['QliroCheckoutShippingMethodChanged'];
export type QliroCheckoutShippingMethodChangedPickupLocation =
  components['schemas']['QliroCheckoutShippingMethodChangedPickupLocation'];
export type QliroCheckoutValidationErrorResponse =
  components['schemas']['QliroCheckoutValidationErrorResponse'];
export type QliroCustomer = components['schemas']['QliroCustomer'];
export type QliroCustomerType = components['schemas']['QliroCustomerType'];
export type QliroError = components['schemas']['QliroError'];
export type QliroOrderManagementStatusRequest =
  components['schemas']['QliroOrderManagementStatusRequest'];
export type QliroUpsell = components['schemas']['QliroUpsell'];
export type Recurring = components['schemas']['Recurring'];
export type RecurringTokenModel = components['schemas']['RecurringTokenModel'];
export type Shipping = components['schemas']['Shipping'];
export type ShippingState = components['schemas']['ShippingState'];
export type State = components['schemas']['State'];
export type Transition = components['schemas']['Transition'];
export type Upsell = components['schemas']['Upsell'];
export type UpsellState = components['schemas']['UpsellState'];
export type UpsellTransaction = components['schemas']['UpsellTransaction'];
export type $defs = Record<string, never>;
export interface operations {
  CartChanged: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description Updated order */
    requestBody?: {
      content: {
        'application/json': components['schemas']['NorceOrder'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatchOperation'][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  UpdateCustomerFromQliroCheckout: {
    parameters: {
      query: {
        /** @description Merchant channel */
        channel: string;
        /** @description Merchant identifier */
        merchant: string;
      };
      header?: never;
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  Notification: {
    parameters: {
      query: {
        /** @description Merchant channel */
        channel: string;
        /** @description Merchant identifier */
        merchant: string;
      };
      header?: never;
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description The Notification data */
    requestBody?: {
      content: {
        'application/json': components['schemas']['QliroCheckoutNotificationRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutPushResponse'];
        };
      };
    };
  };
  Push: {
    parameters: {
      query: {
        /** @description Merchant channel */
        channel: string;
        /** @description Merchant identifier */
        merchant: string;
      };
      header?: never;
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['QliroCheckoutPushRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutPushResponse'];
        };
      };
    };
  };
  SaveRecurringPaymentDetails: {
    parameters: {
      query: {
        /** @description The merchant's sales channel. */
        channel: string;
        /** @description The unique identifier of the merchant. */
        merchant: string;
      };
      header?: never;
      path: {
        /** @description The unique identifier of the order. */
        order_id: string;
        /** @description The unique identifier of the payment. */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description The payment details to be saved. */
    requestBody?: {
      content: {
        'application/json': components['schemas']['MerchantSavedCreditCard'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutPushResponse'];
        };
      };
    };
  };
  ShippingOptionUpdate: {
    parameters: {
      query: {
        /** @description Merchant channel */
        channel: string;
        /** @description Merchant identifier */
        merchant: string;
      };
      header?: never;
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description Shipping option update object */
    requestBody?: {
      content: {
        'application/json': components['schemas']['QliroCheckoutShippingMethodChanged'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  StateChanged: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description Updated order */
    requestBody?: {
      content: {
        'application/json': components['schemas']['NorceOrder'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatchOperation'][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  OrderManagementStatus: {
    parameters: {
      query: {
        /** @description Merchant channel */
        channel: string;
        /** @description Merchant identifier */
        merchant: string;
      };
      header?: never;
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description The order management status data */
    requestBody?: {
      content: {
        'application/json': components['schemas']['QliroOrderManagementStatusRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutPushResponse'];
        };
      };
    };
  };
  UpdatePayment: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description Updated order */
    requestBody?: {
      content: {
        'application/json': components['schemas']['NorceOrder'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatchOperation'][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  CompleteUpsell: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatchOperation'][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  Validate: {
    parameters: {
      query: {
        /** @description Merchant channel */
        channel: string;
        /** @description Merchant identifier */
        merchant: string;
      };
      header?: never;
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    /** @description Qliro order */
    requestBody?: {
      content: {
        'application/json': components['schemas']['GetOrderResponse'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutValidationErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  CreateQliroCheckoutOrderPayment: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutOrder'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  GetQliroCheckoutOrderPayment: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutOrder'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  RemoveQliroCheckoutOrder: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  CreateQliroCheckoutRecurringOrderPayment: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
      };
      cookie?: never;
    };
    /** @description Recurring token that should be used for completing the order */
    requestBody?: {
      content: {
        'application/json': components['schemas']['RecurringTokenModel'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutRecurringOrder'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  CancelOrder: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        order_id: string;
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutOrder'];
        };
      };
    };
  };
  CaptureOrder: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutOrder'];
        };
      };
    };
  };
  Refresh: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        order_id: string;
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  RefundOrder: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Channel identifier
         * @example 1
         */
        'x-channel': string;
        /**
         * @description Merchant identifier.
         * @example norce
         */
        'x-merchant': string;
      };
      path: {
        /** @description Order identifier */
        order_id: string;
        /** @description Payment identifier */
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QliroCheckoutOrder'];
        };
      };
    };
  };
}
